project:
  type: book

book:
  title: "CASA0023 Remotely Sensing Cities and Environments Learning Diary"
  author: "Muhan Yang"
  image: images/pic0.jpg
  cover-image: images/pic0.jpg
  date: "2024/1/18"
  navbar:
    logo: images/pic0.jpg
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "CASA0023"
    style: floating
    reader-mode: true
  repo-url: https://github.com/Muhan-Yang/CASA0023-Remotely-Sensing-Cities-and-Environments
  repo-actions: [edit, issue]
  google-analytics:
    tracking-id: "G-5LZK055F2X"
    anonymize-ip: true
    tools:
    - icon: github
    search: true
  chapters:
    - index.qmd
    - Introduction to Remote Sensing.qmd
    - Xaringan.qmd
    - Corrections.qmd
    - Policy Coastal Erosion Management in Ghana.qmd
    - Google Earth Engine.qmd
    - references.qmd

bibliography: references.bib

website:
  google-analytics:
    tracking-id: "G-5LZK055F2X"
    anonymize-ip: true

format:
  html:
    theme: 
        light: [zephyr]
        dark: [cyborg]
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual



